# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Tue May  7 01:37:15 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 595)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gold-star-11546681624di2ymvxiq0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbCALCULODEPARTICULAS = QtWidgets.QLabel(self.centralwidget)
        self.lbCALCULODEPARTICULAS.setGeometry(QtCore.QRect(9, 9, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.lbCALCULODEPARTICULAS.setFont(font)
        self.lbCALCULODEPARTICULAS.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbCALCULODEPARTICULAS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbCALCULODEPARTICULAS.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbCALCULODEPARTICULAS.setLineWidth(4)
        self.lbCALCULODEPARTICULAS.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCALCULODEPARTICULAS.setWordWrap(True)
        self.lbCALCULODEPARTICULAS.setMargin(17)
        self.lbCALCULODEPARTICULAS.setObjectName("lbCALCULODEPARTICULAS")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 421, 191))
        self.groupBox.setObjectName("groupBox")
        self.leVELOCIDAD = QtWidgets.QLineEdit(self.groupBox)
        self.leVELOCIDAD.setGeometry(QtCore.QRect(139, 127, 271, 20))
        self.leVELOCIDAD.setInputMask("")
        self.leVELOCIDAD.setMaxLength(4)
        self.leVELOCIDAD.setObjectName("leVELOCIDAD")
        self.leDESTINOx = QtWidgets.QLineEdit(self.groupBox)
        self.leDESTINOx.setGeometry(QtCore.QRect(139, 75, 131, 20))
        self.leDESTINOx.setInputMask("")
        self.leDESTINOx.setText("")
        self.leDESTINOx.setMaxLength(3)
        self.leDESTINOx.setObjectName("leDESTINOx")
        self.lbVELOCIDAD = QtWidgets.QLabel(self.groupBox)
        self.lbVELOCIDAD.setGeometry(QtCore.QRect(10, 127, 61, 16))
        self.lbVELOCIDAD.setObjectName("lbVELOCIDAD")
        self.leID = QtWidgets.QLineEdit(self.groupBox)
        self.leID.setGeometry(QtCore.QRect(139, 23, 271, 20))
        self.leID.setMaxLength(8)
        self.leID.setObjectName("leID")
        self.lbDISTANCIA = QtWidgets.QLabel(self.groupBox)
        self.lbDISTANCIA.setGeometry(QtCore.QRect(10, 153, 123, 16))
        self.lbDISTANCIA.setObjectName("lbDISTANCIA")
        self.lbDESTINO = QtWidgets.QLabel(self.groupBox)
        self.lbDESTINO.setGeometry(QtCore.QRect(10, 75, 48, 16))
        self.lbDESTINO.setObjectName("lbDESTINO")
        self.lbID = QtWidgets.QLabel(self.groupBox)
        self.lbID.setGeometry(QtCore.QRect(10, 23, 16, 16))
        self.lbID.setObjectName("lbID")
        self.leORIGENx = QtWidgets.QLineEdit(self.groupBox)
        self.leORIGENx.setGeometry(QtCore.QRect(139, 49, 131, 20))
        self.leORIGENx.setAutoFillBackground(False)
        self.leORIGENx.setInputMask("")
        self.leORIGENx.setText("")
        self.leORIGENx.setMaxLength(3)
        self.leORIGENx.setObjectName("leORIGENx")
        self.lbORIGEN = QtWidgets.QLabel(self.groupBox)
        self.lbORIGEN.setGeometry(QtCore.QRect(10, 49, 43, 16))
        self.lbORIGEN.setObjectName("lbORIGEN")
        self.leCOLORr = QtWidgets.QLineEdit(self.groupBox)
        self.leCOLORr.setGeometry(QtCore.QRect(139, 101, 87, 20))
        self.leCOLORr.setInputMask("")
        self.leCOLORr.setMaxLength(3)
        self.leCOLORr.setObjectName("leCOLORr")
        self.lbCOLOR = QtWidgets.QLabel(self.groupBox)
        self.lbCOLOR.setGeometry(QtCore.QRect(10, 101, 39, 16))
        self.lbCOLOR.setObjectName("lbCOLOR")
        self.leCOLORg = QtWidgets.QLineEdit(self.groupBox)
        self.leCOLORg.setGeometry(QtCore.QRect(235, 101, 86, 20))
        self.leCOLORg.setInputMask("")
        self.leCOLORg.setMaxLength(3)
        self.leCOLORg.setObjectName("leCOLORg")
        self.leCOLORb = QtWidgets.QLineEdit(self.groupBox)
        self.leCOLORb.setGeometry(QtCore.QRect(329, 101, 81, 20))
        self.leCOLORb.setInputMask("")
        self.leCOLORb.setText("")
        self.leCOLORb.setMaxLength(3)
        self.leCOLORb.setObjectName("leCOLORb")
        self.leORIGENy = QtWidgets.QLineEdit(self.groupBox)
        self.leORIGENy.setGeometry(QtCore.QRect(278, 49, 131, 20))
        self.leORIGENy.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.UnitedStates))
        self.leORIGENy.setInputMask("")
        self.leORIGENy.setText("")
        self.leORIGENy.setMaxLength(3)
        self.leORIGENy.setObjectName("leORIGENy")
        self.leDESTINOy = QtWidgets.QLineEdit(self.groupBox)
        self.leDESTINOy.setGeometry(QtCore.QRect(279, 74, 131, 21))
        self.leDESTINOy.setInputMask("")
        self.leDESTINOy.setMaxLength(3)
        self.leDESTINOy.setObjectName("leDESTINOy")
        self.lcdDistancia = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdDistancia.setGeometry(QtCore.QRect(139, 153, 271, 23))
        self.lcdDistancia.setObjectName("lcdDistancia")
        self.pbGuardar = QtWidgets.QPushButton(self.centralwidget)
        self.pbGuardar.setGeometry(QtCore.QRect(20, 280, 91, 31))
        self.pbGuardar.setObjectName("pbGuardar")
        self.pbLimpiar = QtWidgets.QPushButton(self.centralwidget)
        self.pbLimpiar.setGeometry(QtCore.QRect(110, 280, 91, 31))
        self.pbLimpiar.setObjectName("pbLimpiar")
        self.pbMostrar = QtWidgets.QPushButton(self.centralwidget)
        self.pbMostrar.setGeometry(QtCore.QRect(200, 280, 91, 31))
        self.pbMostrar.setObjectName("pbMostrar")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 330, 411, 211))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 90, 451, 451))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 431, 461))
        self.graphicsView.setObjectName("graphicsView")
        self.pbOrdenarDistancia = QtWidgets.QPushButton(self.centralwidget)
        self.pbOrdenarDistancia.setGeometry(QtCore.QRect(610, 10, 121, 31))
        self.pbOrdenarDistancia.setObjectName("pbOrdenarDistancia")
        self.pbOrdenarVelocidad = QtWidgets.QPushButton(self.centralwidget)
        self.pbOrdenarVelocidad.setGeometry(QtCore.QRect(760, 10, 121, 31))
        self.pbOrdenarVelocidad.setObjectName("pbOrdenarVelocidad")
        self.pbVisualizar = QtWidgets.QPushButton(self.centralwidget)
        self.pbVisualizar.setGeometry(QtCore.QRect(460, 10, 121, 31))
        self.pbVisualizar.setObjectName("pbVisualizar")
        self.pbMostrarGrafo = QtWidgets.QPushButton(self.centralwidget)
        self.pbMostrarGrafo.setGeometry(QtCore.QRect(320, 280, 93, 28))
        self.pbMostrarGrafo.setObjectName("pbMostrarGrafo")
        self.origenGrafo = QtWidgets.QLineEdit(self.centralwidget)
        self.origenGrafo.setGeometry(QtCore.QRect(510, 50, 111, 31))
        self.origenGrafo.setMaxLength(8)
        self.origenGrafo.setObjectName("origenGrafo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 60, 55, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 907, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuVer = QtWidgets.QMenu(self.menuBar)
        self.menuVer.setObjectName("menuVer")
        self.menuAlgoritmos = QtWidgets.QMenu(self.menuBar)
        self.menuAlgoritmos.setObjectName("menuAlgoritmos")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.aVerPuntos = QtWidgets.QAction(MainWindow)
        self.aVerPuntos.setObjectName("aVerPuntos")
        self.aPuntosCercanos = QtWidgets.QAction(MainWindow)
        self.aPuntosCercanos.setObjectName("aPuntosCercanos")
        self.actionGrafo = QtWidgets.QAction(MainWindow)
        self.actionGrafo.setObjectName("actionGrafo")
        self.aRecorridoProfundidad = QtWidgets.QAction(MainWindow)
        self.aRecorridoProfundidad.setObjectName("aRecorridoProfundidad")
        self.aRecorridoAnchura = QtWidgets.QAction(MainWindow)
        self.aRecorridoAnchura.setObjectName("aRecorridoAnchura")
        self.aPrim = QtWidgets.QAction(MainWindow)
        self.aPrim.setObjectName("aPrim")
        self.aMostrar = QtWidgets.QAction(MainWindow)
        self.aMostrar.setObjectName("aMostrar")
        self.aKruskal = QtWidgets.QAction(MainWindow)
        self.aKruskal.setObjectName("aKruskal")
        self.menuFile.addAction(self.actionAbrir)
        self.menuFile.addAction(self.actionGuardar)
        self.menuVer.addAction(self.aVerPuntos)
        self.menuVer.addAction(self.actionGrafo)
        self.menuAlgoritmos.addAction(self.aPuntosCercanos)
        self.menuAlgoritmos.addAction(self.aRecorridoProfundidad)
        self.menuAlgoritmos.addAction(self.aRecorridoAnchura)
        self.menuAlgoritmos.addAction(self.aPrim)
        self.menuAlgoritmos.addAction(self.aKruskal)
        self.menuAlgoritmos.addAction(self.aMostrar)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuVer.menuAction())
        self.menuBar.addAction(self.menuAlgoritmos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Calculo de particulas", None, -1))
        self.lbCALCULODEPARTICULAS.setText(QtWidgets.QApplication.translate("MainWindow", "CALCULO DE PARTICULAS", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Ingresa los datos de la particula:", None, -1))
        self.leVELOCIDAD.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "En km/h", None, -1))
        self.leDESTINOx.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.lbVELOCIDAD.setText(QtWidgets.QApplication.translate("MainWindow", "VELOCIDAD:", None, -1))
        self.leID.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "8 digits", None, -1))
        self.lbDISTANCIA.setText(QtWidgets.QApplication.translate("MainWindow", "DISTANCIA EUCLIDIANA:", None, -1))
        self.lbDESTINO.setText(QtWidgets.QApplication.translate("MainWindow", "DESTINO:", None, -1))
        self.lbID.setText(QtWidgets.QApplication.translate("MainWindow", "ID:", None, -1))
        self.leORIGENx.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.lbORIGEN.setText(QtWidgets.QApplication.translate("MainWindow", "ORIGEN:", None, -1))
        self.leCOLORr.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "R", None, -1))
        self.lbCOLOR.setText(QtWidgets.QApplication.translate("MainWindow", "COLOR:", None, -1))
        self.leCOLORg.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "G", None, -1))
        self.leCOLORb.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "B", None, -1))
        self.leORIGENy.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.leDESTINOy.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.pbGuardar.setText(QtWidgets.QApplication.translate("MainWindow", "Guardar", None, -1))
        self.pbLimpiar.setText(QtWidgets.QApplication.translate("MainWindow", "Limpiar", None, -1))
        self.pbMostrar.setText(QtWidgets.QApplication.translate("MainWindow", "Mostrar", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Visualizador", None, -1))
        self.pbOrdenarDistancia.setText(QtWidgets.QApplication.translate("MainWindow", "Ordenar Distancia", None, -1))
        self.pbOrdenarVelocidad.setText(QtWidgets.QApplication.translate("MainWindow", "Ordenar Velocidad", None, -1))
        self.pbVisualizar.setText(QtWidgets.QApplication.translate("MainWindow", "Visualizar", None, -1))
        self.pbMostrarGrafo.setText(QtWidgets.QApplication.translate("MainWindow", "Mostrar Grafo", None, -1))
        self.origenGrafo.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "(x,y)", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Origen: ", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuVer.setTitle(QtWidgets.QApplication.translate("MainWindow", "Ver", None, -1))
        self.menuAlgoritmos.setTitle(QtWidgets.QApplication.translate("MainWindow", "Algoritmos", None, -1))
        self.actionAbrir.setText(QtWidgets.QApplication.translate("MainWindow", "Abrir", None, -1))
        self.actionGuardar.setText(QtWidgets.QApplication.translate("MainWindow", "Guardar Archivo", None, -1))
        self.aVerPuntos.setText(QtWidgets.QApplication.translate("MainWindow", "Puntos", None, -1))
        self.aPuntosCercanos.setText(QtWidgets.QApplication.translate("MainWindow", "Puntos Más cercano", None, -1))
        self.actionGrafo.setText(QtWidgets.QApplication.translate("MainWindow", "Grafo", None, -1))
        self.aRecorridoProfundidad.setText(QtWidgets.QApplication.translate("MainWindow", "Recorrido Profundidad", None, -1))
        self.aRecorridoAnchura.setText(QtWidgets.QApplication.translate("MainWindow", "Recorrido Anchura", None, -1))
        self.aPrim.setText(QtWidgets.QApplication.translate("MainWindow", "Prim", None, -1))
        self.aMostrar.setText(QtWidgets.QApplication.translate("MainWindow", "Mostrar Grafo", None, -1))
        self.aKruskal.setText(QtWidgets.QApplication.translate("MainWindow", "Kruskal", None, -1))

